name: PDGHBan
main: me.mchiappinam.pdghban.Main
version: 1.0
author: mchiappinam
website: http://pdgh.com.br/ & https://hostload.com.br/
depends: [Vault]
commands:
   abc:
      description: Info.
      usage: /<command>